const root=document.querySelector('#guest-root'), token=location.pathname.split('/').filter(Boolean).pop();let currentPath='';
const csrf=()=>decodeURIComponent(document.cookie.split('; ').find(x=>x.startsWith('lanbridge_csrf='))?.split('=').slice(1).join('=')||'');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const size=n=>n<1024?`${n} Б`:`${(n/1024**(Math.floor(Math.log(n)/Math.log(1024)))).toFixed(1)} ${['Б','КБ','МБ','ГБ','ТБ'][Math.min(4,Math.floor(Math.log(n)/Math.log(1024)))]}`;
async function get(path=''){const r=await fetch(`/api/public/${encodeURIComponent(token)}${path?`?path=${encodeURIComponent(path)}`:''}`,{credentials:'same-origin'});const j=await r.json().catch(()=>({}));if(!r.ok)throw Error(j.detail||'Ссылка недоступна');return j}
async function load(path=''){currentPath=path;try{const d=await get(path);if(d.password_required){renderPassword();return}if(!d.is_dir){renderSingle(d);return}renderDirectory(d)}catch(e){root.innerHTML=`<h1>Ссылка недоступна</h1><p class="muted">${esc(e.message)}</p>`}}
function renderPassword(){root.innerHTML=`<h1>Введите пароль</h1><p class="muted">Владелец защитил этот материал паролем.</p><form id="unlock-form" class="guest-password"><input type="password" name="password" autocomplete="current-password" required autofocus placeholder="Пароль ссылки"><button class="button primary">Открыть доступ →</button><div id="guest-error" class="guest-warning"></div></form>`}
function renderSingle(d){root.innerHTML=`<h1>${esc(d.name)}</h1><p class="muted">${esc(d.mime)} · ${size(d.size)} · действует до ${new Date(d.expires_at).toLocaleString('ru-RU')}</p><div class="guest-actions"><a class="button primary" href="/api/public/${encodeURIComponent(token)}/download">↓ Скачать файл</a><span class="muted">Осталось скачиваний: ${Math.max(0,d.max_downloads-d.downloads)}</span></div>`}
function renderDirectory(d){const crumbs=currentPath?currentPath.split('/'):[];root.innerHTML=`<h1>${esc(d.name)}</h1><p class="muted">Общая папка · действует до ${new Date(d.expires_at).toLocaleString('ru-RU')} · осталось скачиваний: ${Math.max(0,d.max_downloads-d.downloads)}</p><div class="guest-breadcrumb"><button data-path="">${esc(d.name)}</button>${crumbs.map((x,i)=>` / <button data-path="${esc(crumbs.slice(0,i+1).join('/'))}">${esc(x)}</button>`).join('')}</div><div>${d.items.map(x=>`<div class="guest-row"><span class="guest-row-icon">${x.is_dir?'▰':'·'}</span><div class="guest-row-main"><strong>${esc(x.name)}</strong><small>${x.is_dir?'Папка':size(x.size)}</small></div>${x.is_dir?`<button class="button-secondary button-small" data-path="${esc(x.path)}">Открыть</button>`:`<a class="button-secondary button-small" href="/api/public/${encodeURIComponent(token)}/download?path=${encodeURIComponent(x.path)}">Скачать</a>`}</div>`).join('')||'<p class="muted">Эта папка пуста.</p>'}</div><div class="guest-actions"><a class="button primary" href="/api/public/${encodeURIComponent(token)}/download?path=${encodeURIComponent(currentPath)}">↓ Скачать папку целиком (.zip)</a></div>`}
document.addEventListener('click',e=>{const b=e.target.closest('[data-path]');if(b&&b.tagName==='BUTTON')load(b.dataset.path)});
document.addEventListener('submit',async e=>{if(e.target.id!=='unlock-form')return;e.preventDefault();const password=new FormData(e.target).get('password');const r=await fetch(`/api/public/${encodeURIComponent(token)}/unlock`,{method:'POST',credentials:'same-origin',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf()},body:JSON.stringify({password})});const d=await r.json().catch(()=>({}));if(!r.ok){document.querySelector('#guest-error').textContent=d.detail||'Не удалось проверить пароль';return}load(currentPath)});
load();
